# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Unit Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install numpy
        pip3 install requests
        python3 -m pip install -f https://download.pytorch.org/whl/cpu/torch-1.9.0-cp37-cp37m-manylinux2014_aarch64.whl
    - name: Test with unittest
      run: |
        python3 -m unittest
